[workspace]
authors = ["tom-yneuro <tom@yneuro.com>"]
channels = ["conda-forge"]
name = "skada-sprint"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=1.24"
scipy = ">=1.10"
scikit-learn = ">=1.5.0"
pot = ">=0.9.3"
pytorch = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"
skorch = ">=1.1.0,<2"
ipython = ">=9.3.0,<10"
pre-commit = ">=4.2.0,<5"
matplotlib = ">=3.10.3,<4"
ipykernel = ">=6.29.5,<7"
python = "<3.13"
pandas = ">=2.3.0,<3"

[pypi-dependencies]
skada= { path = ".", editable = true }